# Generated by Django 5.2.9 on 2026-06-08 15:28

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=255, verbose_name='Код метки')),
                ('color', models.CharField(default='#3B82F6', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Укажите HEX-цвет в формате #3B82F6.')], verbose_name='Цвет')),
                ('icon', models.CharField(blank=True, help_text='Например: bank, cash, card', max_length=100, verbose_name='Иконка')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_labels', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Банковская метка',
                'verbose_name_plural': 'Банковские метки',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название проекта')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=255, verbose_name='Код проекта')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('started_at', models.DateField(blank=True, null=True, verbose_name='Дата начала проекта')),
                ('finished_at', models.DateField(blank=True, null=True, verbose_name='Дата окончания проекта')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_projects', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FinanceOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('month', models.IntegerField(choices=[(1, 'Январь'), (2, 'Февраль'), (3, 'Март'), (4, 'Апрель'), (5, 'Май'), (6, 'Июнь'), (7, 'Июль'), (8, 'Август'), (9, 'Сентябрь'), (10, 'Октябрь'), (11, 'Ноябрь'), (12, 'Декабрь')], editable=False, verbose_name='Месяц')),
                ('quarter', models.IntegerField(choices=[(1, '1 квартал'), (2, '2 квартал'), (3, '3 квартал'), (4, '4 квартал')], editable=False, verbose_name='Финансовый квартал')),
                ('movement_type', models.CharField(choices=[('expense', 'Трата'), ('income', 'Доход'), ('saving', 'Сбережение')], max_length=20, verbose_name='Тип движения денег')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма RUB')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('source_object_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='ID исходной записи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('bank_label', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_operations', to='core.banklabel', verbose_name='Банковская метка')),
                ('source_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype', verbose_name='Тип исходной записи')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_operations', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_operations', to='core.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Финансовая операция',
                'verbose_name_plural': 'Финансовые операции',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='banklabel',
            index=models.Index(fields=['user', 'is_active'], name='core_bankla_user_id_baaf39_idx'),
        ),
        migrations.AddConstraint(
            model_name='banklabel',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_bank_label_name_per_user'),
        ),
        migrations.AddConstraint(
            model_name='banklabel',
            constraint=models.UniqueConstraint(fields=('user', 'slug'), name='unique_bank_label_slug_per_user'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['user', 'is_active'], name='core_projec_user_id_1f79a6_idx'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_project_name_per_user'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('user', 'slug'), name='unique_project_slug_per_user'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(condition=models.Q(('finished_at__isnull', True), ('started_at__isnull', True), ('finished_at__gte', models.F('started_at')), _connector='OR'), name='project_finished_after_started'),
        ),
        migrations.AddIndex(
            model_name='financeoperation',
            index=models.Index(fields=['user', 'date'], name='core_financ_user_id_f2b383_idx'),
        ),
        migrations.AddIndex(
            model_name='financeoperation',
            index=models.Index(fields=['user', 'month', 'quarter'], name='core_financ_user_id_60cb38_idx'),
        ),
        migrations.AddIndex(
            model_name='financeoperation',
            index=models.Index(fields=['project', 'date'], name='core_financ_project_661acc_idx'),
        ),
        migrations.AddIndex(
            model_name='financeoperation',
            index=models.Index(fields=['source_content_type', 'source_object_id'], name='core_financ_source__956764_idx'),
        ),
        migrations.AddConstraint(
            model_name='financeoperation',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='finance_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='financeoperation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('source_content_type__isnull', True), ('source_object_id__isnull', True)), models.Q(('source_content_type__isnull', False), ('source_object_id__isnull', False)), _connector='OR'), name='finance_source_fields_together'),
        ),
        migrations.AddConstraint(
            model_name='financeoperation',
            constraint=models.UniqueConstraint(condition=models.Q(('source_object_id__isnull', False)), fields=('user', 'source_content_type', 'source_object_id'), name='unique_finance_operation_source_per_user'),
        ),
    ]
