# Generated by Codex on 2026-05-29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_categories(apps, schema_editor):
    ExpenseCategory = apps.get_model('expenses', 'ExpenseCategory')
    for slug, name in [
        ('fuel', 'Заправка'),
        ('service', 'Сервис'),
        ('repair', 'Ремонт'),
        ('insurance', 'Страховка'),
        ('parking', 'Парковка'),
        ('wash', 'Мойка'),
        ('toll', 'Платная дорога'),
        ('tax', 'Налог'),
        ('other', 'Другое'),
    ]:
        ExpenseCategory.objects.get_or_create(slug=slug, defaults={'name': name})


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forge', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=50, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Категория расходов',
                'verbose_name_plural': 'Категории расходов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата траты')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[
                    django.core.validators.MinValueValidator(0)
                ], verbose_name='Сумма (₽)')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('source_app', models.CharField(blank=True, max_length=50, verbose_name='Приложение-источник')),
                ('source_model', models.CharField(blank=True, max_length=50, verbose_name='Модель-источник')),
                ('source_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='ID источника')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные данные')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                               related_name='expenses', to='expenses.expensecategory',
                                               verbose_name='Категория')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                           related_name='expenses', to=settings.AUTH_USER_MODEL,
                                           verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Трата',
                'verbose_name_plural': 'Траты',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['user', 'date'], name='expenses_e_user_id_6068bf_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['user', 'category'], name='expenses_e_user_id_436ff3_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['source_app', 'source_model', 'source_id'], name='expenses_e_source_52d65c_idx'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.UniqueConstraint(condition=models.Q(('source_app__gt', ''), ('source_model__gt', '')),
                                               fields=('source_app', 'source_model', 'source_id'),
                                               name='unique_expense_source'),
        ),
        migrations.RunPython(seed_categories, migrations.RunPython.noop),
    ]
