# Generated by Django 5.2.9 on 2026-06-12 11:19

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UtilityService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='название')),
                ('category', models.CharField(choices=[('housing', 'Содержание жилья'), ('cold_water', 'Холодная вода'), ('hot_water', 'Горячая вода'), ('sewerage', 'Водоотведение'), ('electricity', 'Электроэнергия'), ('heating', 'Отопление'), ('gas', 'Газ'), ('waste', 'Обращение с ТКО'), ('capital_repair', 'Капитальный ремонт'), ('security', 'Безопасность'), ('insurance', 'Страхование'), ('other', 'Прочее')], db_index=True, default='other', max_length=30, verbose_name='категория')),
                ('default_unit', models.CharField(blank=True, help_text='Например: м³, кВт·ч, Гкал, м².', max_length=30, verbose_name='единица измерения')),
                ('is_optional', models.BooleanField(default=False, help_text='Например, добровольное страхование.', verbose_name='добровольная услуга')),
            ],
            options={
                'verbose_name': 'вид услуги',
                'verbose_name_plural': 'виды услуг',
                'ordering': ('category', 'name'),
            },
        ),
        migrations.CreateModel(
            name='UtilityDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_period', models.DateField(db_index=True, help_text='Первый день расчетного месяца, например 2026-05-01.', verbose_name='расчетный период')),
                ('issued_at', models.DateField(blank=True, null=True, verbose_name='дата квитанции')),
                ('due_at', models.DateField(blank=True, null=True, verbose_name='оплатить до')),
                ('provider', models.CharField(blank=True, max_length=255, verbose_name='поставщик или расчетный центр')),
                ('document_number', models.CharField(blank=True, max_length=100, verbose_name='номер документа')),
                ('source_file', models.FileField(blank=True, upload_to='utility_documents/%Y/%m/', verbose_name='исходный файл')),
                ('source_hash', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='SHA-256 файла')),
                ('accrued_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='начислено')),
                ('adjustment_total', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Уменьшение хранится отрицательным числом.', max_digits=14, verbose_name='перерасчет')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Долг положительный, переплата отрицательная.', max_digits=14, verbose_name='долг или переплата на начало')),
                ('credited_payment', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='оплата, учтенная в квитанции')),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='итого к оплате')),
                ('optional_amount_due', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='итого с добровольными услугами')),
                ('notes', models.TextField(blank=True, verbose_name='примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='добавлено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
            ],
            options={
                'verbose_name': 'квитанция ЖКХ',
                'verbose_name_plural': 'квитанции ЖКХ',
                'ordering': ('-billing_period', '-id'),
                'indexes': [models.Index(fields=['billing_period', 'provider'], name='billHome_ut_billing_8b3c11_idx')],
            },
        ),
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='номер счетчика')),
                ('kind', models.CharField(choices=[('individual', 'Индивидуальный'), ('common', 'Общедомовой')], default='individual', max_length=20, verbose_name='тип счетчика')),
                ('unit', models.CharField(max_length=30, verbose_name='единица измерения')),
                ('verification_due_at', models.DateField(blank=True, null=True, verbose_name='поверка до')),
                ('active', models.BooleanField(default=True, verbose_name='используется')),
                ('notes', models.TextField(blank=True, verbose_name='примечания')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meters', to='billHome.utilityservice', verbose_name='услуга')),
            ],
            options={
                'verbose_name': 'счетчик',
                'verbose_name_plural': 'счетчики',
                'ordering': ('service', 'serial_number', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(blank=True, help_text='Исходный текст нужен для проверки автоматического импорта.', max_length=255, verbose_name='название в квитанции')),
                ('scope', models.CharField(choices=[('individual', 'Индивидуальное потребление'), ('common', 'Общедомовые нужды'), ('housing', 'Жилищная услуга'), ('other', 'Прочее')], default='individual', max_length=20, verbose_name='область потребления')),
                ('calculation_method', models.CharField(choices=[('meter', 'По счетчику'), ('standard', 'По нормативу'), ('area', 'По площади'), ('fixed', 'Фиксированная сумма'), ('other', 'Другой способ'), ('unknown', 'Неизвестно')], default='unknown', max_length=20, verbose_name='способ расчета')),
                ('tariff_zone', models.CharField(blank=True, help_text='Например: день, ночь, пик.', max_length=50, verbose_name='тарифная зона')),
                ('quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='объем')),
                ('unit', models.CharField(blank=True, max_length=30, verbose_name='единица измерения')),
                ('tariff', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='тариф')),
                ('accrued', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='начислено')),
                ('adjustment', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Уменьшение хранится отрицательным числом.', max_digits=14, verbose_name='перерасчет')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='долг или переплата')),
                ('credited_payment', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='учтенная оплата')),
                ('amount_due', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='к оплате')),
                ('adjustment_reason', models.CharField(blank=True, max_length=500, verbose_name='основание перерасчета')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='billHome.utilitydocument', verbose_name='квитанция')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='billHome.utilityservice', verbose_name='услуга')),
            ],
            options={
                'verbose_name': 'начисление',
                'verbose_name_plural': 'начисления',
                'ordering': ('document', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_at', models.DateField(db_index=True, verbose_name='дата оплаты')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='сумма')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='добавлено')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='billHome.utilitydocument', verbose_name='квитанция')),
            ],
            options={
                'verbose_name': 'оплата ЖКХ',
                'verbose_name_plural': 'оплаты ЖКХ',
                'ordering': ('-paid_at', '-id'),
                'indexes': [models.Index(fields=['paid_at', 'amount'], name='billHome_pa_paid_at_09e683_idx')],
            },
        ),
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_date', models.DateField(db_index=True, verbose_name='дата показания')),
                ('tariff_zone', models.CharField(blank=True, help_text='Например: день или ночь.', max_length=50, verbose_name='тарифная зона')),
                ('previous_value', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='предыдущее показание')),
                ('current_value', models.DecimalField(decimal_places=6, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='текущее показание')),
                ('consumption', models.DecimalField(blank=True, decimal_places=6, help_text='Можно сохранить значение из квитанции или вычислить по показаниям.', max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='расход')),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='billHome.meter', verbose_name='счетчик')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meter_readings', to='billHome.utilitydocument', verbose_name='квитанция')),
            ],
            options={
                'verbose_name': 'показание счетчика',
                'verbose_name_plural': 'показания счетчиков',
                'ordering': ('-reading_date', 'meter', 'tariff_zone'),
                'indexes': [models.Index(fields=['meter', 'reading_date'], name='billHome_me_meter_i_78b493_idx')],
                'constraints': [models.UniqueConstraint(fields=('meter', 'reading_date', 'tariff_zone'), name='unique_meter_reading_per_date_and_zone'), models.CheckConstraint(condition=models.Q(('previous_value__isnull', True), ('current_value__gte', models.F('previous_value')), _connector='OR'), name='meter_current_not_below_previous')],
            },
        ),
        migrations.AddConstraint(
            model_name='meter',
            constraint=models.UniqueConstraint(condition=models.Q(('serial_number', ''), _negated=True), fields=('service', 'serial_number', 'kind'), name='unique_numbered_meter_per_service'),
        ),
        migrations.AddIndex(
            model_name='charge',
            index=models.Index(fields=['service', 'document'], name='billHome_ch_service_b77778_idx'),
        ),
        migrations.AddIndex(
            model_name='charge',
            index=models.Index(fields=['scope', 'calculation_method'], name='billHome_ch_scope_63b65a_idx'),
        ),
        migrations.AddConstraint(
            model_name='charge',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__isnull', True), ('quantity__gte', Decimal('0')), _connector='OR'), name='charge_quantity_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='charge',
            constraint=models.CheckConstraint(condition=models.Q(('tariff__isnull', True), ('tariff__gte', Decimal('0')), _connector='OR'), name='charge_tariff_nonnegative'),
        ),
    ]
