# Generated by Django 5.2.9 on 2026-05-29 07:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GasStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название АЗС')),
                ('number', models.CharField(blank=True, max_length=50, verbose_name='Номер АЗС')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('company', models.CharField(blank=True, max_length=100, verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'АЗС',
                'verbose_name_plural': 'АЗС',
                'ordering': ['company', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('brand', models.CharField(blank=True, max_length=50, null=True, verbose_name='Марка')),
                ('model', models.CharField(blank=True, max_length=50, null=True, verbose_name='Модель')),
                ('year', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)], verbose_name='Год выпуска')),
                ('license_plate', models.CharField(blank=True, help_text='у123хм456', max_length=20, verbose_name='Госномер')),
                ('initial_odometer', models.IntegerField(default=0, verbose_name='Начальный пробег')),
                ('current_odometer', models.IntegerField(default=0, verbose_name='Текущий пробег')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Транспортное средство',
                'verbose_name_plural': 'Транспортные средства',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FuelPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('fuel_type', models.CharField(choices=[('АИ-92', 'АИ-92'), ('АИ-95', 'АИ-95'), ('АИ-98', 'АИ-98'), ('ДТ', 'Дизель'), ('ГАЗ', 'Газ')], max_length=20, verbose_name='Тип топлива')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена (₽/л)')),
                ('gas_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forge.gasstation', verbose_name='АЗС')),
            ],
            options={
                'verbose_name': 'Цена топлива',
                'verbose_name_plural': 'Цены на топливо',
                'ordering': ['-date', 'fuel_type'],
                'unique_together': {('date', 'fuel_type', 'gas_station')},
            },
        ),
        migrations.CreateModel(
            name='Refueling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата заправки')),
                ('month', models.IntegerField(blank=True, choices=[(1, 'Январь'), (2, 'Февраль'), (3, 'Март'), (4, 'Апрель'), (5, 'Май'), (6, 'Июнь'), (7, 'Июль'), (8, 'Август'), (9, 'Сентябрь'), (10, 'Октябрь'), (11, 'Ноябрь'), (12, 'Декабрь')], null=True, verbose_name='Месяц')),
                ('quarter', models.IntegerField(blank=True, choices=[(1, '1 квартал'), (2, '2 квартал'), (3, '3 квартал'), (4, '4 квартал')], null=True, verbose_name='Квартал')),
                ('mileage', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Пробег с прошлой заправки (км)')),
                ('fuel_quantity', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество топлива (л)')),
                ('price_per_liter', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена за литр (₽)')),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Общая стоимость (₽)')),
                ('service_operation', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='Работа сервиса')),
                ('fuel_type', models.CharField(blank=True, choices=[('АИ-92', 'АИ-92'), ('АИ-95', 'АИ-95'), ('АИ-98', 'АИ-98'), ('ДТ', 'Дизель'), ('ГАЗ', 'Газ')], max_length=20, null=True, verbose_name='Тип топлива')),
                ('is_full_tank', models.BooleanField(blank=True, default=False, null=True, verbose_name='Полный бак')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Скидка (₽)')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('gas_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forge.gasstation', verbose_name='АЗС')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refuelings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forge.vehicle', verbose_name='Транспортное средство')),
            ],
            options={
                'verbose_name': 'Заправка',
                'verbose_name_plural': 'Заправки',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['date'], name='forge_refue_date_717270_idx'), models.Index(fields=['vehicle'], name='forge_refue_vehicle_e14ac8_idx'), models.Index(fields=['fuel_type'], name='forge_refue_fuel_ty_b650cf_idx')],
            },
        ),
        migrations.CreateModel(
            name='FuelStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(verbose_name='Период')),
                ('period_type', models.CharField(choices=[('month', 'Месяц'), ('quarter', 'Квартал'), ('year', 'Год')], max_length=10, verbose_name='Тип периода')),
                ('total_distance', models.IntegerField(default=0, verbose_name='Общий пробег (км)')),
                ('total_fuel', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Общее топливо (л)')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общая стоимость (₽)')),
                ('avg_consumption', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Средний расход (л/100км)')),
                ('avg_price', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Средняя цена (₽/л)')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forge.vehicle', verbose_name='Транспортное средство')),
            ],
            options={
                'verbose_name': 'Статистика расхода',
                'verbose_name_plural': 'Статистика расхода',
                'ordering': ['-period', 'vehicle'],
                'unique_together': {('vehicle', 'period', 'period_type')},
            },
        ),
    ]
