# Generated by Django 6.0 on 2025-12-20 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0003_alter_vehicle_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refueling',
            name='gas_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forge.gasstation', verbose_name='АЗС'),
        ),
    ]
