# Generated by Django 6.0 on 2026-01-10 14:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0004_alter_refueling_gas_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refueling',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Скидка (₽)'),
        ),
        migrations.AlterField(
            model_name='refueling',
            name='is_full_tank',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Полный бак'),
        ),
        migrations.AlterField(
            model_name='refueling',
            name='month',
            field=models.IntegerField(blank=True, choices=[(1, 'Январь'), (2, 'Февраль'), (3, 'Март'), (4, 'Апрель'), (5, 'Май'), (6, 'Июнь'), (7, 'Июль'), (8, 'Август'), (9, 'Сентябрь'), (10, 'Октябрь'), (11, 'Ноябрь'), (12, 'Декабрь')], null=True, verbose_name='Месяц'),
        ),
        migrations.AlterField(
            model_name='refueling',
            name='quarter',
            field=models.IntegerField(blank=True, choices=[(1, '1 квартал'), (2, '2 квартал'), (3, '3 квартал'), (4, '4 квартал')], null=True, verbose_name='Квартал'),
        ),
        migrations.AlterField(
            model_name='refueling',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Общая стоимость (₽)'),
        ),
    ]
