# Generated by Django 6.0 on 2026-01-10 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0005_alter_refueling_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refueling',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('АИ-92', 'АИ-92'), ('АИ-95', 'АИ-95'), ('АИ-98', 'АИ-98'), ('ДТ', 'Дизель'), ('ГАЗ', 'Газ')], max_length=20, null=True, verbose_name='Тип топлива'),
        ),
        migrations.AlterField(
            model_name='refueling',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forge.vehicle', verbose_name='Транспортное средство'),
        ),
    ]
