# Generated by Django 4.2.27 on 2026-01-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0006_alter_refueling_fuel_type_alter_refueling_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name=' тип топливо')),
            ],
        ),
        migrations.AddField(
            model_name='gasstation',
            name='fuel_types',
            field=models.ManyToManyField(to='forge.fuel'),
        ),
    ]
