# Generated by Django 4.2.27 on 2026-02-06 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0007_fuel_gasstation_fuel_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasstation',
            name='fuel_types',
        ),
        migrations.DeleteModel(
            name='Fuel',
        ),
    ]
