# Generated by Django 4.2.27 on 2026-02-07 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0008_remove_gasstation_fuel_types_delete_fuel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refueling',
            name='odometer',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='current_odometer',
            field=models.IntegerField(default=0, verbose_name='Текущий пробег'),
        ),
    ]
