# Generated by Django 4.2.27 on 2026-02-07 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0009_remove_refueling_odometer_vehicle_current_odometer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refueling',
            name='vehicle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='forge.vehicle', verbose_name='Транспортное средство'),
            preserve_default=False,
        ),
    ]
