# Generated by Django 4.2.27 on 2026-04-26 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0010_alter_refueling_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='refueling',
            name='service_operation',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='Работа сервиса'),
        ),
    ]
